name: turu_sore
description: Smart ISP Management System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.1
  lucide_icons: ^0.1.0 # Alternatif jika ingin icon mirip react
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
